# Generated by Django 3.0 on 2019-12-06 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20191206_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('visitor_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='orders.Visitor')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('orders.visitor',),
        ),
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_num', models.IntegerField(default=0)),
                ('exp_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                              django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(19)])),
                ('cvv', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1),
                                                                   django.core.validators.MaxValueValidator(999)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Customer')),
            ],
        ),
    ]
