# Generated by Django 3.0 on 2019-12-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_payment_info_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='u_id',
            new_name='user',
        ),
    ]
