# Generated by Django 3.0 on 2019-12-06 23:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191206_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_f_name', models.CharField(max_length=100)),
                ('d_l_name', models.CharField(max_length=100)),
                ('d_phone', models.CharField(max_length=20)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('coordinates', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Delivery')),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Dish')),
            ],
        ),
    ]
