# Generated by Django 3.0 on 2019-12-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191210_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
    ]
