# Generated by Django 3.0 on 2019-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0008_auto_20191210_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
