# Generated by Django 3.0 on 2019-12-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0009_auto_20191210_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='shipping',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='orders.ShippingAddress'),
            preserve_default=False,
        ),
    ]
