# Generated by Django 3.0 on 2019-12-10 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0010_visitor_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='shipping',
        ),
    ]
