# Generated by Django 3.0 on 2019-12-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_visitor_shipping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_Info',
            new_name='PaymentInfo',
        ),
        migrations.AddField(
            model_name='visitor',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.ShippingAddress'),
        ),
    ]
