# Generated by Django 3.0 on 2019-12-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_visitor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
