# Generated by Django 3.0 on 2019-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191211_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
