# Generated by Django 3.0 on 2019-12-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20191211_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Cook'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_cooked',
            field=models.BooleanField(default=False),
        ),
    ]
